### ISSUE TITLE
Todo first release

### ISSUE THREAD

**Issue by yannham** [nickel-lang/nickel-nix#2]
TODO:

- [x] Add a readme that explains why `--impure` is needed
- [x] Rename `MkShell` to `Shell` (and make a pass on exported symbols: `Shell`, `Derivation` and `string_hack`)
- [x] Remove string hacks
- [ ] Create examples for derivation, and string context

**Comment by yannham** [comment]
We kept nix string hacks, and a derivation has been postponed. Closing for now, as the first release happened.
